name = "Mathew's Server Mods"
author = "Mach50"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a17adb5d22155ac91b71480e4bbc63eab6423fa2a4ff8f2ead04e48857ee974"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
